/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class AppCustomIcon {
  AppCustomIcon._();

  static const _kFontFam = 'CustomIcon';

  static const IconData drawer_cosmetics = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData drawer_flow_tree = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData drawer_groceries = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData drawer_home_outline = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData drawer_like_heart = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData drawer_log_out = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData drawer_manage_payment = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData drawer_money_transaction = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData icon_mail = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData drawer_phone_ring = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData drawer_privacy_policy = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData drawer_profile_user = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData drawer_review_star = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData drawer_shirt = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData drawer_shopping_bag_cart = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData drawer_television = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData drawer_terms_condition = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData drawer_my_order = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData icon_pwd_eye = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData icon_pwd_key = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData icon_user = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData icon_cart = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData icon_location = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData icon_call = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData icon_24hrs = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData icon_100_guarantee = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData icon_free_shipping = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData icon_return = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData icon_default_camera = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData mail_2 = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData icon_edit = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData icon_delete = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData icon_envelope = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData icon_white_logo_ebazaar = const IconData(0xe842, fontFamily: _kFontFam);
  static const IconData icon_secure = const IconData(0xe821, fontFamily: _kFontFam);
  static const IconData icon_share = const IconData(0xe822, fontFamily: _kFontFam);

}
